name: stl
channels:
  - http://conda.anaconda.org/gurobi
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.5.7
  - cartopy=0.21.1
  - charset-normalizer=3.2.0
  - contourpy=1.1.0
  - cycler=0.11.0
  - fonttools=4.41.0
  - freetype=2.12.1
  - geos=3.11.2
  - idna=3.4
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.21.1
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=8.2.0
  - libdeflate=1.18
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=13.1.0
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - libgomp=13.1.0
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - libnghttp2=1.52.0
  - libnsl=2.0.0
  - libopenblas=0.3.23
  - libpng=1.6.39
  - libsqlite=3.42.0
  - libssh2=1.11.0
  - libstdcxx-ng=13.1.0
  - libtiff=4.5.1
  - libuuid=2.38.1
  - libwebp-base=1.3.1
  - libxcb=1.15
  - libzlib=1.2.13
  - matplotlib-base=3.7.2
  - munkres=1.1.4
  - ncurses=6.4
  - numpy=1.25.1
  - openjpeg=2.5.0
  - openssl=3.1.1
  - packaging=23.1
  - pip=23.2
  - platformdirs=3.9.1
  - pooch=1.7.0
  - proj=9.2.1
  - pthread-stubs=0.4
  - pyparsing=3.0.9
  - pyproj=3.6.0
  - pyshp=2.3.1
  - pysocks=1.7.1
  - python=3.11.4
  - python-dateutil=2.8.2
  - python_abi=3.11
  - readline=8.2
  - requests=2.31.0
  - scipy=1.11.1
  - setuptools=68.0.0
  - shapely=2.0.1
  - six=1.16.0
  - sqlite=3.42.0
  - tk=8.6.12
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - urllib3=2.0.4
  - wheel=0.40.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - zstd=1.5.2
  - pip:
    - altair==5.0.1
    - attrs==23.1.0
    - bleach==6.0.0
    - blinker==1.6.2
    - bokeh==2.4.3
    - cachetools==5.3.1
    - certifi==2023.5.7
    - cftime==1.6.2
    - click==8.1.6
    - click-plugins==1.1.1
    - cligj==0.7.2
    - colorcet==3.0.1
    - decorator==5.1.1
    - fiona==1.9.4.post1
    - geopandas==0.13.2
    - geoviews==1.9.6
    - gitdb==4.0.10
    - gitpython==3.1.32
    - holoviews==1.16.2
    - hvplot==0.8.4
    - importlib-metadata==6.8.0
    - jinja2==3.1.2
    - jsonschema==4.18.4
    - jsonschema-specifications==2023.7.1
    - markdown==3.4.3
    - markdown-it-py==3.0.0
    - markupsafe==2.1.3
    - mdurl==0.1.2
    - netcdf4==1.6.4
    - networkx==3.1
    - pandas==2.0.3
    - panel==0.14.4
    - param==1.13.0
    - pillow==9.5.0
    - plotly==5.15.0
    - protobuf==4.23.4
    - pyarrow==12.0.1
    - pyct==0.5.0
    - pydeck==0.8.0
    - pygments==2.15.1
    - pympler==1.0.1
    - pytz==2023.3
    - pytz-deprecation-shim==0.1.0.post0
    - pyviz-comms==2.3.2
    - pyyaml==6.0.1
    - referencing==0.30.0
    - rich==13.4.2
    - rpds-py==0.9.2
    - smmap==5.0.0
    - streamlit==1.25.0
    - tenacity==8.2.2
    - toml==0.10.2
    - toolz==0.12.0
    - tornado==6.3.2
    - tqdm==4.65.0
    - tzdata==2023.3
    - tzlocal==4.3.1
    - validators==0.20.0
    - watchdog==3.0.0
    - webencodings==0.5.1
    - xarray==2023.7.0
    - zipp==3.16.2
prefix: /home/fneum/miniconda3/envs/stl
